name: Discord Commit

on:
  workflow_call:
    secrets:
      DISCORD_COMMIT_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Qbox-project/pipeline-pling@v1
        with:
          webhook-url: ${{ secrets.DISCORD_COMMIT_WEBHOOK }}
